import {KEY,today,uid,clamp,freshState,loadState,persist,validateState,award,petAction,petStage} from './store.js';
import {esc,icon,button,field,toast,modal,download,bindBackdrop} from './ui.js';
import {PATHS,QUEST_STEPS} from './explore-data.js';
import {ARENAS,LENSES,debateExport} from './debate-data.js';
import {WORLDS,startLife,makeChoice} from './story-data.js';
import {defaultSurprise,planSurprise,publicCard,encodeCard,decodeCard,planText,standaloneCard,calendarFile} from './surprise-engine.js';
import {shell,homeView,exploreView,debateView,livesView,petView,surpriseView,giftView,journalView} from './views.js';
import {mountLab} from './labs.js';
let storage;try{storage=window.localStorage;}catch{}
const loaded=loadState(storage);let S=loaded.state;
const U={exploreTab:'paths',questId:null,questStep:0,debateTab:'new',claim:'',arena:'custom',lens:'direct',confidence:70,pauseDebate:false,petName:'',petElement:'moss',petTemperament:'curious',petSpeech:'',petAnimation:'',catchCount:0,catchActive:false,catchX:45,catchY:45,surprise:defaultSurprise(),surpriseTab:'new',editSurpriseId:null,giftOpen:false,giftReturn:null,pendingRestore:null};
let cleanupLab=()=>{},saveWarned=false,route='home',installPrompt;
const app=document.getElementById('app');
function save(){const ok=persist(S,storage);if(!ok&&!saveWarned){saveWarned=true;toast('Device storage is unavailable. Export a backup before you leave.');}return ok;}
function grant(key,title,kind,points){const earned=award(S,key,title,kind,points);save();return earned;}
function pathProgress(id){return S.explore[id]||(S.explore[id]={step:0,done:[],answers:{},notes:'',reflection:'',complete:false});}
function go(to){if(location.hash.slice(1)===to)render();else location.hash=to;}
function closeModal(){document.getElementById('modal').close();}
function formData(form){return Object.fromEntries(new FormData(form));}
function celebrate(){if(!S.preferences.motion||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const d=document.createElement('div');d.className='celebrate';d.setAttribute('aria-hidden','true');d.innerHTML=Array.from({length:22},()=>`<i style="--x:${Math.random()*100}%;--d:${Math.random()*.35}s;--c:${['#b4f6ce','#f6bd8a','#cbb9fa'][Math.floor(Math.random()*3)]}"></i>`).join('');document.body.append(d);setTimeout(()=>d.remove(),2500);}
function render(keepScroll=false){const y=window.scrollY;cleanupLab();cleanupLab=()=>{};route=location.hash.slice(1)||'home';document.body.classList.toggle('reduce-motion',!S.preferences.motion);if(route.startsWith('gift=')){try{app.innerHTML=giftView(decodeCard(route.slice(5)),U.giftOpen);}catch(e){app.innerHTML=`<main class="reveal-page"><h1>This card could not be opened.</h1><p>The link may be incomplete. Ask the sender for the full link or the downloaded reveal card.</p><a href="#home" class="btn secondary spaced">Open Elsewhere</a></main>`;}window.scrollTo(0,0);return;}
  const [section,id,qid]=route.split('/');let view;
  if(section==='explore'){if(PATHS.some(x=>x.id===id))pathProgress(id);if(id==='quest'&&qid)U.questId=qid;view=exploreView(S,U,id);}
  else if(section==='debate')view=debateView(S,U,id);
  else if(section==='lives')view=livesView(S,U,id);
  else if(section==='pet')view=petView(S,U);
  else if(section==='surprise')view=surpriseView(S,U,id);
  else if(section==='journal')view=journalView(S);
  else view=homeView(S);
  app.innerHTML=shell(S,section,view);
  if(section==='explore'&&PATHS.some(t=>t.id===id)&&pathProgress(id).step===2)cleanupLab=mountLab(id);
  if(keepScroll)window.scrollTo(0,y);else window.scrollTo(0,0);
  document.title=section==='home'?'Elsewhere — your personal playground':`${{explore:'Rabbit holes',debate:'The other side',lives:'Parallel lives',pet:'Your creature',surprise:'Made for someone',journal:'Your collection'}[section]||'Your playground'} · Elsewhere`;
}
function settings(){modal('Make it yours',`<form id="settings-form">${field('What should we call you?',`<input name="name" required maxlength="32" value="${esc(S.profile.name)}" autocomplete="given-name">`)}<label class="check-row"><input type="checkbox" name="motion" ${S.preferences.motion?'checked':''}><span>Gentle animations</span></label><button class="btn primary spaced" type="submit">Save preferences</button></form><div class="divider"></div><h3>Keep your world safe</h3><p style="font-size:.9rem;margin:10px 0 18px">Progress lives in this browser on this device. A backup lets you move it to another phone or restore it after browser data is cleared.</p><div class="actions-wrap">${button(icon('download')+' Export backup','export-backup','secondary')}${button('Import backup','import-backup','secondary')}</div><input type="file" id="backup-input" accept=".json,application/json" hidden><div class="divider"></div><h3>A place on your home screen</h3><p style="font-size:.9rem;margin:10px 0">${installPrompt?'Install Elsewhere for a full-screen experience.':'iPhone: open in Safari, tap Share, then Add to Home Screen. Android: use your browser’s Install app or Add to Home screen option.'}</p>${installPrompt?button('Install Elsewhere','install','secondary'):''}<p class="source-note" id="offline-status">${navigator.serviceWorker?.controller?'Offline files are available. Source links still need internet.':'The first complete online load prepares the app for offline use.'}</p><div class="divider"></div><details><summary>About this version</summary><p>Elsewhere 1.0 uses authored lessons, structured reflection questions, branching fiction and local game rules. It does not call a live AI model, track you, or require an account. Your companion belongs to this app.</p><p>Surprise links contain only the public card. Anyone with a link can open that card. Exported backups contain your private writing; keep them somewhere you trust.</p></details>${button('Reset this device’s progress','reset-confirm','danger','style="margin-top:22px"')}`);}
async function copyText(text,label='Copied to clipboard.'){try{await navigator.clipboard.writeText(text);toast(label);}catch{modal('Copy this link',`${field('Select and copy the full link',`<textarea readonly rows="5" id="copy-fallback">${esc(text)}</textarea>`)}<p class="source-note">Your browser did not allow automatic copying.</p>`);const el=document.getElementById('copy-fallback');el.focus();el.select();}}
function exportPath(id){const t=PATHS.find(x=>x.id===id),p=S.explore[id];if(!t||!p)return;download(`elsewhere-${id}-notes.md`,`# ${t.title}\n\n## My explanation\n${p.reflection||'(Not written yet)'}\n\n## Field notes\n${p.notes||'(Not written yet)'}\n\n## Next question\n${t.next}\n\n## Sources\n${t.sources.map(s=>`- [${s.title}](${s.url})`).join('\n')}\n`,'text/markdown');}
function exportLife(id){const w=WORLDS.find(x=>x.id===id),r=S.lives[id];if(!w||!r)return;download(`elsewhere-${id}-${r.name.replace(/[^a-z0-9]/gi,'-')}.txt`,`${w.title}\nA life lived by ${r.name}\n\n${r.history.map((h,i)=>`${i+1}. ${w.nodes[h.node]?.title||h.node}\nChoice: ${h.choice}\n${h.consequence}`).join('\n\n')}\n\n${w.nodes[r.node]?.title}\n${w.nodes[r.node]?.text.replaceAll('{name}',r.name)}\n\nWhat I carried: ${r.inventory.join(', ')||'Nothing yet'}\nCourage: ${r.stats.courage}; Trust: ${r.stats.trust}; Insight: ${r.stats.insight}\n`);}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(a.startsWith('lab-'))return;e.preventDefault();const [action,id,x,z]=a.split(':');
  try{switch(action){
  case 'settings':settings();break;
  case 'close-modal':closeModal();break;
  case 'explore-tab':U.exploreTab=id;render(true);break;
  case 'new-quest':modal('What has you curious?',`<form id="quest-form">${field('Your obsession',`<input name="title" required minlength="3" maxlength="100" placeholder="Why do cities feel alive?" autocomplete="off">`)}${field('Your first question (optional)',`<textarea name="question" maxlength="500" rows="3" placeholder="What is the thing you most want to understand?"></textarea>`)}<button class="btn primary" type="submit">Open an investigation ${icon('arrow')}</button></form>`);break;
  case 'open-quest':U.questId=id;U.questStep=0;go(`explore/quest/${id}`);break;
  case 'quest-step':U.questStep=clamp(id,0,5);render();break;
  case 'quest-next':{const q=S.quests.find(q=>q.id===U.questId),step=+id;if(!q)return;if((q.steps[step]||'').trim().length<20){document.getElementById('quest-error').textContent='Write at least 20 characters before completing this stage.';return;}grant(`quest:${q.id}:${step}`,`${q.title}: ${QUEST_STEPS[step].title}`,'explore',10);if(step<5){U.questStep=step+1;render();}else if(q.steps.some(s=>s.trim().length<20)||q.steps.length<6){document.getElementById('quest-error').textContent='Return to each earlier stage and add your working notes before finishing.';}else{grant(`quest:${q.id}:complete`,`Completed an investigation: ${q.title}`,'explore',25);toast('Investigation saved. Keep following the question.');U.exploreTab='quests';go('explore');celebrate();}break;}
  case 'export-quest':{const q=S.quests.find(q=>q.id===id);if(q)download('elsewhere-investigation.md',`# ${q.title}\n\n${q.question}\n\n`+QUEST_STEPS.map((s,i)=>`## ${s.title}\n${q.steps[i]||''}`).join('\n\n'),'text/markdown');break;}
  case 'lesson-step':if(PATHS.some(t=>t.id===id)){pathProgress(id).step=clamp(x,0,5);save();render();}break;
  case 'lesson-next':{const t=PATHS.find(t=>t.id===id),p=pathProgress(id);if(!t)return;const error=document.getElementById('lesson-error');if(p.step===3&&!t.quiz.every((q,i)=>p.answers[i]===q.answer)){error.textContent='Answer all four checks correctly. The explanations will help you try again.';return;}if(p.step===4&&p.reflection.trim().length<30){error.textContent='Write at least 30 characters for your explanation before continuing.';return;}if(p.step===5&&p.complete){go('explore');return;}if(p.step===5&&![0,1,2,3,4].every(i=>p.done.includes(i))){error.textContent='Finish each earlier stage using Continue, then return here to complete the path.';return;}if(!p.done.includes(p.step))p.done.push(p.step);grant(`path:${id}:${p.step}`,`${t.title}: ${['first question','a useful model','the experiment','understanding checked','an explanation','next questions'][p.step]}`,'explore',10);if(p.step<5)p.step++;else{p.complete=true;grant(`path:${id}:complete`,`Completed ${t.title}`,'explore',25);celebrate();toast('Path completed. Your field notes are saved.');}save();render();break;}
  case 'quiz':{const t=PATHS.find(t=>t.id===id);if(!t?.quiz[+x]||!t.quiz[+x].options[+z])return;pathProgress(id).answers[+x]=+z;save();render(true);break;}
  case 'export-path':exportPath(id);break;
  case 'debate-tab':U.debateTab=id;U.pauseDebate=true;render(true);break;
  case 'debate-arena':{const arena=ARENAS.find(v=>v.id===id);if(arena){U.arena=id;U.claim=arena.claim;render();document.getElementById('debate-form')?.scrollIntoView({block:'start'});}break;}
  case 'debate-lens':if(LENSES.some(l=>l.id===id)){U.lens=id;render(true);}break;
  case 'debate-round':if(S.activeDebate){S.activeDebate.round=clamp(id,0,4);save();render();}break;
  case 'debate-pause':U.pauseDebate=true;save();go('debate');break;
  case 'debate-resume':U.pauseDebate=false;go('debate');break;
  case 'debate-discard':modal('Start a new challenge?',`<p>Your unfinished challenge will be removed. Completed reflections will stay in your collection.</p>`,button('Keep thinking','close-modal','secondary')+button('Start again','debate-discard-confirm','danger'));break;
  case 'debate-discard-confirm':S.activeDebate=null;U.pauseDebate=false;U.debateTab='new';save();closeModal();go('debate');break;
  case 'debate-new':U.pauseDebate=true;U.debateTab='new';go('debate');break;
  case 'export-debate':{const d=S.debates.find(x=>x.id===id);if(d)download('elsewhere-idea-challenge.txt',debateExport(d));break;}
  case 'story-choice':{const w=WORLDS.find(w=>w.id===id),r=S.lives[id];if(!w||!r)return;const result=makeChoice(w,r,+x);if(!result.ok)return;if(result.ending){if(!S.endings.some(e=>e.world===id&&e.ending===r.ending))S.endings.push({world:id,ending:r.ending,title:w.nodes[r.node].title,at:Date.now()});grant(`ending:${id}:${r.ending}`,`Found an ending: ${w.nodes[r.node].title}`,'lives',40);celebrate();}else grant(`story:${id}:${r.node}`,`${w.title}: ${w.nodes[r.node].title}`,'lives',5);save();render();document.getElementById('main')?.focus({preventScroll:true});break;}
  case 'restart-life':{const w=WORLDS.find(w=>w.id===id);if(!w)return;modal('Live it differently?',`<p>Start ${esc(w.title)} from the beginning. Discovered endings stay in your collection. Download the current life first if you want to keep its complete choices.</p>`,button('Keep this life','close-modal','secondary')+button('Start a new life',`restart-life-confirm:${id}`));break;}
  case 'restart-life-confirm':delete S.lives[id];save();closeModal();go('lives/'+id);break;
  case 'story-journal':{const r=S.lives[id],w=WORLDS.find(w=>w.id===id);if(!r||!w)return;modal('The choices that brought you here',`${r.history.map((h,i)=>`<div class="history-item"><div class="eyebrow">${i+1}. ${w.nodes[h.node]?.title||'A moment'}</div><h4 style="margin-top:9px">${esc(h.choice)}</h4><p>${esc(h.consequence)}</p></div>`).join('')||'<p>Your story has just begun.</p>'}`,button('Download this life','export-life:'+id,'secondary'));break;}
  case 'export-life':exportLife(id);break;
  case 'pet-element':if(['moss','ember','moon','tide'].includes(id)){U.petElement=id;render(true);}break;
  case 'pet-action':{const result=petAction(S,id);U.petSpeech=result.message;if(result.ok){U.petAnimation=id;save();render(true);setTimeout(()=>{U.petAnimation='';document.querySelector('.pet-visual')?.classList.remove('action-'+id);},1000);}else toast(result.message);break;}
  case 'pet-customise':if(S.pet)petCustomise();break;
  case 'catch-start':U.catchCount=0;U.catchActive=true;U.catchX=42;U.catchY=40;render(true);document.getElementById('catch-target')?.focus({preventScroll:true});break;
  case 'catch-star':if(U.catchActive&&S.pet){U.catchCount++;if(U.catchCount>=10){U.catchActive=false;S.pet.joy=clamp(S.pet.joy+10,0,100);S.pet.bond=clamp(S.pet.bond+5,0,100);const earned=grant('pet:starlight:'+today(),`${S.pet.name}: ten stars found together`,'pet',15);U.petSpeech='Ten little stars. One very good human.';render(true);toast(earned?'Ten stars! +15 sparks and growth.':'Ten stars found together. A lovely little break.');celebrate();}else{U.catchX=8+Math.round(Math.random()*68);U.catchY=22+Math.round(Math.random()*48);const star=document.getElementById('catch-target');star.style.left=U.catchX+'%';star.style.top=U.catchY+'%';star.setAttribute('aria-label','Catch star '+(U.catchCount+1));document.getElementById('catch-score').textContent=U.catchCount+' / 10 stars';}}break;
  case 'surprise-tab':U.surpriseTab=id;render(true);break;
  case 'surprise-style':if(['hunt','memory','night','distance'].includes(id)){U.surprise.style=id;render(true);}break;
  case 'edit-surprise':{const p=S.surprises.find(p=>p.id===id);if(p){U.surprise={...p.input};U.editSurpriseId=id;U.surpriseTab='new';go('surprise');}break;}
  case 'delete-surprise':modal('Remove this plan?',`<p>This removes the organiser’s plan from this device. Previously shared reveal cards will still work.</p>`,button('Keep it','close-modal','secondary')+button('Remove plan','delete-surprise-confirm:'+id,'danger'));break;
  case 'delete-surprise-confirm':S.surprises=S.surprises.filter(x=>x.id!==id);save();closeModal();render(true);break;
  case 'preview-surprise':{const s=S.surprises.find(p=>p.id===id);if(s){U.giftReturn=route;U.giftOpen=false;go('gift='+encodeCard(publicCard(planSurprise(s.input))));}break;}
  case 'open-gift':U.giftOpen=true;render();celebrate();break;
  case 'gift-back':U.giftOpen=false;go(U.giftReturn||'home');break;
  case 'share-surprise':{const s=S.surprises.find(p=>p.id===id);if(!s)return;const card=publicCard(planSurprise(s.input));const url=new URL(location.href);url.hash='gift='+encodeCard(card);if(navigator.share){try{await navigator.share({title:'A little surprise for '+card.to,text:'Someone made a moment just for you.',url:url.href});}catch(err){if(err.name!=='AbortError')await copyText(url.href,'Reveal link copied.');}}else await copyText(url.href,'Reveal link copied.');break;}
  case 'export-surprise':{const s=S.surprises.find(p=>p.id===id);if(s)download('elsewhere-surprise-plan.txt',planText(planSurprise(s.input)));break;}
  case 'download-card':{const s=S.surprises.find(p=>p.id===id);if(s)download('a-little-surprise.html',standaloneCard(publicCard(planSurprise(s.input))),'text/html');break;}
  case 'calendar-surprise':{const s=S.surprises.find(p=>p.id===id);if(s)download('elsewhere-surprise-date.ics',calendarFile(planSurprise(s.input)),'text/calendar');break;}
  case 'print':window.print();break;
  case 'export-backup':download(`elsewhere-backup-${today()}.json`,JSON.stringify(S,null,2),'application/json');toast('Backup downloaded. Keep it somewhere you can find it.');break;
  case 'import-backup':document.getElementById('backup-input')?.click();break;
  case 'restore-backup':if(U.pendingRestore){S=U.pendingRestore;U.pendingRestore=null;U.pauseDebate=false;save();closeModal();go('home');toast('Your Elsewhere world has been restored.');}break;
  case 'reset-confirm':modal('Reset this device?',`<p>This deletes local notes, stories, your creature and surprise plans from this browser. Export a backup first if you want to keep them.</p>`,button('Keep my progress','close-modal','secondary')+button('Reset everything','reset-all','danger'));break;
  case 'reset-all':S=freshState();U.pauseDebate=false;U.surprise=defaultSurprise();U.editSurpriseId=null;U.questId=null;U.catchActive=false;save();closeModal();go('home');toast('A fresh beginning.');break;
  case 'install':if(installPrompt){await installPrompt.prompt();installPrompt=null;closeModal();}break;
  }}catch(err){console.error('Elsewhere action:',err);toast(err.message||'That did not work. Your saved progress is still here.');}
});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.draft){U[el.dataset.draft]=el.type==='range'?Number(el.value):el.value;if(el.dataset.draft==='claim')U.arena='custom';if(el.dataset.draft==='confidence')document.getElementById('confidence-value').textContent=el.value+'%';}
  if(el.dataset.surprise)U.surprise[el.dataset.surprise]=el.value;
  if(el.dataset.live==='after'&&S.activeDebate){S.activeDebate.after=+el.value;document.getElementById('after-value').textContent=el.value+'%';save();}
  if(el.dataset.save){const [type,id,index]=el.dataset.save.split(':');let status;
    if(['notes','reflection'].includes(type)&&PATHS.some(t=>t.id===id)){pathProgress(id)[type]=el.value;status=type+'-status';}
    if(type==='quest'){const q=S.quests.find(q=>q.id===id);if(q)q.steps[+index]=el.value;status='quest-status';}
    if(type==='debate-answer'&&S.activeDebate)S.activeDebate.answers[S.activeDebate.round]=el.value;
    const ok=save();if(status&&document.getElementById(status))document.getElementById(status).textContent=ok?'Saved on this device.':'Not saved: export a backup before leaving.';
  }
});
document.addEventListener('change',async e=>{const el=e.target;if(el.dataset.surprise)U.surprise[el.dataset.surprise]=el.value;
  if(el.dataset.check){const [id,index]=el.dataset.check.split(':'),p=S.surprises.find(p=>p.id===id);if(p){p.checks=p.checks.filter(x=>x!==index);if(el.checked)p.checks.push(index);save();}}
  if(el.id==='backup-input'&&el.files?.[0]){const file=el.files[0];try{if(file.size>10000000)throw new Error('Choose an Elsewhere backup smaller than 10 MB.');U.pendingRestore=validateState(JSON.parse(await file.text()));closeModal();modal('Restore this world?',`<p>This backup contains ${U.pendingRestore.profile.sparks} sparks, ${U.pendingRestore.debates.length} completed reflections and ${U.pendingRestore.surprises.length} surprise plans.</p><p style="margin-top:13px">It will replace this device’s current progress. Export the current world first if you want to keep both.</p>`,button('Keep current world','close-modal','secondary')+button('Restore backup','restore-backup'));}catch(err){toast(err.message||'This file is not a valid backup.');}el.value='';}
});
document.addEventListener('submit',e=>{const f=e.target;if(!['settings-form','quest-form','debate-form','debate-round-form','life-start-form','pet-create-form','pet-customise-form','surprise-form'].includes(f.id))return;e.preventDefault();const d=formData(f);
  if(f.id==='settings-form'){S.profile.name=d.name.trim()||'Wanderer';S.preferences.motion=!!d.motion;save();closeModal();render(true);toast('A little more you.');}
  if(f.id==='quest-form'){const q={id:uid(),title:d.title.trim(),question:d.question.trim(),steps:[d.question.trim(),'','','','',''],created:Date.now()};S.quests.unshift(q);U.questId=q.id;U.questStep=0;save();closeModal();go('explore/quest/'+q.id);}
  if(f.id==='debate-form'){if(S.activeDebate){toast('Resume or discard your saved challenge before starting another.');return;}S.activeDebate={id:uid(),claim:d.claim.trim(),arena:U.arena,lens:U.lens,confidence:+d.confidence,after:+d.confidence,round:0,answers:[],revision:'',complete:false,created:Date.now()};U.pauseDebate=false;save();render();}
  if(f.id==='debate-round-form'){const a=S.activeDebate;if(!a)return;const answer=d.answer.trim();if(answer.length<20){toast('Give your response at least 20 characters.');return;}a.answers[a.round]=answer;if(a.round<4)a.round++;else{if(a.answers.length<5||a.answers.some(t=>t.trim().length<20)){toast('Complete each earlier round before finishing.');return;}a.after=+d.after;a.revision=answer;a.complete=true;S.debates.unshift({...a});S.activeDebate=null;grant('debate:'+a.id,'Reconsidered: '+a.claim.slice(0,90),'debate',35);save();go('debate/'+a.id);celebrate();return;}save();render();}
  if(f.id==='life-start-form'){const w=WORLDS.find(w=>w.id===f.dataset.world);if(w){S.lives[w.id]=startLife(w,d.name.trim());save();render();}}
  if(f.id==='pet-create-form'){if(S.pet)return;S.pet={name:d.name.trim()||'Miso',element:U.petElement,temperament:d.temperament,born:Date.now(),bond:20,energy:80,joy:75,xp:0,actions:{},memories:[],accessory:'none',habitat:'grove'};grant('pet:born','Met '+S.pet.name,'pet',10);save();render();celebrate();toast('Welcome to your world, '+S.pet.name+'.');}
  if(f.id==='pet-customise-form'){if(!S.pet)return;const p=S.pet;p.name=d.name.trim()||p.name;const accessoryMin={none:0,starlight:60,crown:160,halo:350};if(p.xp>=accessoryMin[d.accessory])p.accessory=d.accessory;const habitatMin={grove:0,moon:60,shore:160};if(p.xp>=habitatMin[d.habitat])p.habitat=d.habitat;save();closeModal();render(true);toast('Looking very much like themselves.');}
  if(f.id==='surprise-form'){const p=planSurprise({...d,style:U.surprise.style}).input;let saved=S.surprises.find(p=>p.id===U.editSurpriseId);if(saved){saved.input=p;saved.checks=[];}else{saved={id:uid(),input:p,checks:[],created:Date.now()};S.surprises.unshift(saved);}grant('surprise:'+saved.id,'Made a surprise for '+p.recipient,'surprise',25);U.surprise=defaultSurprise();U.editSurpriseId=null;save();go('surprise/'+saved.id);toast('Your plan is ready and saved.');}
});
function petCustomise(){const p=S.pet;modal('A little more '+p.name,`<form id="pet-customise-form">${field('Their name',`<input name="name" required maxlength="24" value="${esc(p.name)}">`)}${field('A little adornment',`<select name="accessory">${[['none','Just themselves',0],['starlight','Starlight',60],['crown','Tiny crown',160],['halo','Celestial halo',350]].map(([id,n,min])=>`<option value="${id}" ${p.accessory===id?'selected':''} ${p.xp<min?'disabled':''}>${n}${p.xp<min?' · needs '+min+' growth':''}</option>`).join('')}</select>`)}${field('Their quiet corner',`<select name="habitat">${[['grove','The quiet grove',0],['moon','The moon garden',60],['shore','The starlit shore',160]].map(([id,n,min])=>`<option value="${id}" ${p.habitat===id?'selected':''} ${p.xp<min?'disabled':''}>${n}${p.xp<min?' · needs '+min+' growth':''}</option>`).join('')}</select>`)}<p class="source-note">Shared activities unlock new places and little adornments.</p><button class="btn primary spaced" type="submit">Save their look</button></form>`);}
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();document.getElementById('main')?.focus();});
bindBackdrop();window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#gift='))U.giftOpen=false;render();});window.addEventListener('pagehide',()=>cleanupLab());document.addEventListener('visibilitychange',()=>{if(document.hidden){cleanupLab();}else if(route.startsWith('explore/')&&document.getElementById('lab')){cleanupLab=mountLab(route.split('/')[1]);}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
render();if(loaded.error)setTimeout(()=>toast(loaded.error),400);if(!storage)setTimeout(()=>toast('Storage is unavailable. Use Export backup to keep your progress.'),800);
if('serviceWorker' in navigator&&location.protocol!=='file:'){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{const el=document.getElementById('offline-status');if(el)el.textContent='Offline setup was unavailable. You can still use the app while online.';});});}
if(document.modelContext?.registerTool){const life=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  register({name:'read_elsewhere_progress',title:'Read playground progress',description:'Read completion counts and creature stage. Does not return private notes or surprise contents.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return {sparks:S.profile.sparks,pathsCompleted:Object.values(S.explore).filter(p=>p.complete).length,reflections:S.debates.length,endings:S.endings.length,creatureStage:S.pet?petStage(S.pet.xp):null,surprisePlans:S.surprises.length};}});
  register({name:'open_elsewhere_experience',title:'Open an experience',description:'Navigate to one of the five experiences or the collection. Does not complete an activity or change saved progress.',inputSchema:{type:'object',properties:{experience:{type:'string',enum:['home','explore','debate','lives','pet','surprise','journal']}},required:['experience'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||Object.keys(input).length!==1||!['home','explore','debate','lives','pet','surprise','journal'].includes(input.experience))throw new Error('Choose a valid experience.');go(input.experience);await new Promise(resolve=>requestAnimationFrame(resolve));return {opened:input.experience};}});
  window.addEventListener('pagehide',()=>life.abort(),{once:true});
}
