export const ARENAS=[
{id:'comfort',label:'Comfort vs growth',claim:'A comfortable life is better than an ambitious one.',counter:'Comfort can protect what matters, but it can also let fear choose your boundaries. What distinguishes contentment from avoidance?',steelman:'The strongest case for ambition might be about agency and contribution, not status. Can you make that case without mocking it?',test:'Imagine two equally healthy people: one content with little, one energised by a difficult goal. What would make your claim true for both?'},
{id:'loyalty',label:'Loyalty vs honesty',claim:'Loyalty to the people I love should come before honesty.',counter:'Someone can feel protected by a lie today and betrayed by it later. How are you separating their interests from your wish to avoid discomfort?',steelman:'Make the best case for telling a painful truth with care. Under what conditions could that be the more loyal act?',test:'Imagine the person later discovers what you concealed. What rule could you explain to them without changing it just for your case?'},
{id:'money',label:'Enough vs more',claim:'More money would solve most of my dissatisfaction.',counter:'Money can remove real constraints. But which specific dissatisfaction would remain if your practical needs were comfortably met?',steelman:'Argue that meaning, attention and relationships can be limiting factors even when resources increase. Keep material hardship in view.',test:'List three frustrations. For each, specify the mechanism by which more money would help, and one reason it might not.'},
{id:'freedom',label:'Freedom vs commitment',claim:'Keeping my options open is better than making a long commitment.',counter:'Open options have value, but depth often comes from closing some doors. What are you giving up by postponing a choice?',steelman:'Make the best case for a commitment that creates freedom through trust, practice or stability.',test:'Pick one reversible commitment you could try for a month. What observation would help you compare it with keeping every option open?'},
{id:'talent',label:'Talent vs practice',claim:'Natural talent matters more than consistent practice.',counter:'How are you measuring talent independently of prior opportunity and practice? The label may be doing more work than you think.',steelman:'Build the strongest case for structured practice while acknowledging that starting points and ceilings can differ.',test:'Choose one narrow skill. How would you compare two learning approaches without pretending that one small test proves a universal rule?'},
{id:'privacy',label:'Privacy vs convenience',claim:'Personalisation is worth giving up a lot of privacy.',counter:'A convenient feature and an irreversible disclosure are not the same kind of trade. What information, recipient and retention period does your claim actually allow?',steelman:'Make the case for a person who values privacy even when they have nothing embarrassing to hide.',test:'Name one service you would keep and one data permission you would remove. What principle explains both choices?'},
{id:'forgiveness',label:'Forgiveness vs boundaries',claim:'Forgiving someone means giving them another chance.',counter:'Forgiveness, trust and access to your life can be separate decisions. What changes if you stop treating them as a package?',steelman:'Make the best case for forgiving while maintaining a firm boundary. Then make the best case for gradual reconciliation.',test:'What observable behaviour would justify rebuilding trust? What would tell you the boundary needs to remain?'},
{id:'certainty',label:'Instinct vs evidence',claim:'My gut feeling is usually enough to make a good decision.',counter:'In what environments has your instinct received reliable feedback? Confidence in familiar situations may not transfer to unfamiliar ones.',steelman:'Argue for slowing down and checking evidence, while admitting that analysis can also be incomplete or biased.',test:'Choose an upcoming low-stakes decision. Record your prediction and reasons now. What result would count as a meaningful miss?'}
];
export const LENSES=[{id:'gentle',name:'Curious friend',description:'Patient questions. Room to think.',voice:'Mira'},{id:'direct',name:'Honest sceptic',description:'Direct questions. No easy exits.',voice:'Rowan'},{id:'rigorous',name:'Cross-examiner',description:'Definitions, evidence, exceptions.',voice:'Vale'}];
export const ROUNDS=['Define it','Face the countercase','Switch sides','Test it','Revise it'];
export function debatePrompt(d,round){
  const a=ARENAS.find(a=>a.id===d.arena);
  const generic=[`What exactly do you mean by “${d.claim}”? Define the key terms, say who it applies to, and name one exception.`,a?.counter||'What is the strongest realistic case in which your claim fails? Identify a person or situation your current wording overlooks.',a?.steelman||'Argue for the opposing view as if an intelligent person you respect held it. What evidence, values or experiences could make it reasonable?',a?.test||'Design a small, reversible test of your claim. State a prediction, an observation that would challenge it, and what you would do next.','Write the strongest version of your position now. Keep what survived, narrow what was too broad, and say what remains uncertain.'];
  if(d.lens==='gentle')return ['Let’s make this precise. '+generic[0],generic[1]+' You can keep the parts you still believe.',generic[2],generic[3],generic[4]][round];
  if(d.lens==='rigorous')return [generic[0]+' Avoid undefined words such as “better” or “always”.',generic[1]+' A real counterexample must address your claim, not an easier substitute.',generic[2]+' Name the strongest supporting reason before criticising it.',generic[3]+' What result would force you to update, rather than reinterpret the test?',generic[4]+' Separate your evidence from your values.'][round];
  return generic[round];
}
export function responseChecklist(answer){const s=answer.toLowerCase();return {specific: /\b(for example|for instance|when|if|because|such as)\b/.test(s),uncertainty:/\b(might|could|uncertain|depends|sometimes|unless|except|not always|i don't know)\b/.test(s),testable:/\b(test|compare|measure|observe|evidence|predict|record|check)\b/.test(s)};}
export function responseProbe(answer){
  if(!answer?.trim())return '';
  const s=answer.toLowerCase();
  const absolute=s.match(/\b(always|never|everyone|nobody|guaranteed)\b/);
  if(absolute)return `You used “${absolute[0]}”. Is that absolute wording necessary, or would one realistic exception force you to narrow it?`;
  if(/\b(feel|feels|feeling|instinct|gut)\b/.test(s))return 'You mentioned a feeling or instinct. What observation would help you separate that signal from the conclusion you draw from it?';
  if(/\b(family|love|loyalty|friend|partner)\b/.test(s))return 'You mentioned a relationship. How could you check what the other person values without assuming it is the same thing you value?';
  if(/\b(test|measure|compare|evidence)\b/.test(s))return 'You mentioned evidence or a test. What result would count against your position, and how will you avoid explaining that result away?';
  if(!/\b(example|because|when|if)\b/.test(s))return 'Could you ground the previous answer in one specific situation? A concrete example will make the next question more useful.';
  return 'Look back at your last answer. Which part is directly observed, and which part is an interpretation or a value you are choosing?';
}
export function debateExport(d){return `ELSEWHERE · IDEA CHALLENGE\n\nClaim: ${d.claim}\nStyle: ${LENSES.find(x=>x.id===d.lens)?.name}\nConfidence: ${d.confidence}% → ${d.after}%\n\n`+d.answers.map((x,i)=>`${i+1}. ${ROUNDS[i]}\n${debatePrompt(d,i)}\n\n${x}\n`).join('\n')+'\nReflection exercise, not a factual verdict. No live AI was used.\n';}
