import {esc,icon,button} from './ui.js';
export function labMarkup(id){
  if(id==='space')return `<div class="lab-display"><span class="eyebrow">NEARBY CLOCK, PER DISTANT HOUR</span><strong id="lab-value" class="big-number">42.4 min</strong><p id="lab-detail">At 2 event-horizon radii</p></div><label for="distance">Distance from the centre · horizon radii</label><input id="distance" type="range" min="1.1" max="10" value="2" step="0.1"><p>Ideal stationary clocks outside a nonrotating black hole. The boundary is at r = 1; the slider stays outside it.</p>`;
  if(id==='ocean')return `<div class="lab-display"><span class="eyebrow">APPROXIMATE ABSOLUTE PRESSURE</span><strong id="lab-value" class="big-number">101 atm</strong><p id="lab-detail">1,000 metres below the surface</p></div><label for="depth">Depth · metres</label><input id="depth" type="range" min="0" max="11000" value="1000" step="100"><p>Model: 1 + depth / 10 atmospheres. Rounded for exploration; not a diving or equipment calculator.</p>`;
  if(id==='mind')return `<div class="lab-display" id="stroop-display"><span class="eyebrow">A SMALL ATTENTION EXPERIMENT</span><p style="margin:15px 0">Tap the ink colour. Ignore the word.</p>${button('Try 8 trials','lab-stroop-start','secondary')}<small>No timer. No ranking.</small></div><div class="row" id="stroop-options"></div><p class="source-note">Colour difficult to distinguish? You can skip the activity and use the experiment-design prompt instead.</p>`;
  if(id==='sound')return `<div class="lab-display"><svg class="wave" viewBox="0 0 400 100" role="img" aria-label="Sound waveform"><path id="wave-path" d="" fill="none" stroke="#eee0a5" stroke-width="2"/></svg><strong class="big-number" id="lab-value">220 Hz</strong></div><label for="frequency">Frequency · hertz</label><input id="frequency" type="range" min="100" max="800" step="10" value="220"><label for="wave-shape">Wave shape</label><select id="wave-shape"><option value="sine">Sine · smooth</option><option value="triangle">Triangle · brighter</option><option value="square">Square · buzzy</option></select><div class="row spaced">${button(icon('sound')+' Play quietly','lab-sound','secondary')}<span id="sound-status" class="muted">Sound is off</span></div><p class="source-note">Volume is deliberately low. Use your device’s volume control for comfort. Sound stops when you leave this page.</p>`;
  if(id==='strategy')return `<p>Payoffs are <strong>you, partner</strong>. These are fictional points.</p><table class="matrix"><thead><tr><th scope="col">Your move</th><th scope="col">Partner cooperates</th><th scope="col">Partner defects</th></tr></thead><tbody><tr><th scope="row">Cooperate</th><td data-cell="cc">3, 3</td><td data-cell="cd">0, 5</td></tr><tr><th scope="row">Defect</th><td data-cell="dc">5, 0</td><td data-cell="dd">1, 1</td></tr></tbody></table><label for="your-move">Your move</label><select id="your-move"><option value="c">Cooperate</option><option value="d">Defect</option></select><label for="their-move">Partner’s move</label><select id="their-move"><option value="c">Cooperate</option><option value="d">Defect</option></select><p id="lab-detail" class="spaced" aria-live="polite"></p>`;
  return `<div class="lab-display"><span class="eyebrow" id="lens-type">REAL, INVERTED IMAGE</span><strong class="big-number" id="lab-value">−1.00×</strong><p id="lab-detail">Image at 2.00 focal lengths</p></div><label for="object-distance">Object distance · focal lengths</label><input id="object-distance" type="range" min="0.3" max="4" step="0.1" value="2"><p>Thin-lens model with f = 1. A negative magnification means the image is inverted; its absolute value gives the size ratio.</p>`;
}
export function mountLab(id){const root=document.getElementById('lab');if(!root)return ()=>{};let audio,osc,gain,on=false,trial=0,correct=0;const colorNames=['MINT','PEACH','BLUE','LILAC'],colors=['#b4f6ce','#f6bd8a','#80d2ed','#d4a8f8'];const trials=[[0,0],[1,2],[3,1],[2,2],[0,3],[1,1],[2,0],[3,2]];
  const value=root.querySelector('#lab-value'),detail=root.querySelector('#lab-detail');
  function update(){
    if(id==='space'){const r=+root.querySelector('#distance').value;value.textContent=`${(60*Math.sqrt(1-1/r)).toFixed(1)} min`;detail.textContent=`At ${r.toFixed(1)} event-horizon radii`;}
    if(id==='ocean'){const d=+root.querySelector('#depth').value;value.textContent=`${(1+d/10).toLocaleString()} atm`;detail.textContent=`${d.toLocaleString()} metres below the surface`;}
    if(id==='sound'){const f=+root.querySelector('#frequency').value,shape=root.querySelector('#wave-shape').value;value.textContent=`${f} Hz`;const points=Array.from({length:401},(_,i)=>{const a=i/400*(f/55)*Math.PI*2;let y=Math.sin(a);if(shape==='square')y=y>=0?1:-1;if(shape==='triangle')y=2/Math.PI*Math.asin(Math.sin(a));return `${i===0?'M':'L'}${i},${50-y*32}`;}).join(' ');root.querySelector('#wave-path').setAttribute('d',points);if(osc){osc.frequency.value=f;osc.type=shape;}}
    if(id==='strategy'){const a=root.querySelector('#your-move').value,b=root.querySelector('#their-move').value;root.querySelectorAll('[data-cell]').forEach(el=>el.classList.toggle('highlight',el.dataset.cell===a+b));const values={cc:[3,3],cd:[0,5],dc:[5,0],dd:[1,1]}[a+b];detail.textContent=`You get ${values[0]}; your partner gets ${values[1]}. ${a+b==='dd'?'Both would have received more with mutual cooperation.':'Now change only the other player’s move and compare.'}`;}
    if(id==='light'){const u=+root.querySelector('#object-distance').value;let mag,v;if(Math.abs(u-1)<.001){value.textContent='∞';detail.textContent='At the focus: image distance tends to infinity.';root.querySelector('#lens-type').textContent='PARALLEL EMERGING RAYS';return;}v=u/(u-1);mag=-v/u;value.textContent=`${mag<0?'−':'+'}${Math.abs(mag).toFixed(2)}×`;detail.textContent=`Image at ${v.toFixed(2)} focal lengths ${v<0?'(object side)':''}`;root.querySelector('#lens-type').textContent=v>0?'REAL, INVERTED IMAGE':'VIRTUAL, UPRIGHT IMAGE';}
  }
  function showTrial(){const d=root.querySelector('#stroop-display'),options=root.querySelector('#stroop-options');if(trial>=trials.length){d.innerHTML=`<span class="eyebrow">YOUR EIGHT TRIALS</span><strong class="big-number">${correct} / 8</strong><p>You named the ink correctly ${correct} times. What might change with practice?</p>`;options.innerHTML=button('Try again','lab-stroop-start','secondary');return;}const [word,ink]=trials[trial];d.innerHTML=`<span class="eyebrow">TRIAL ${trial+1} OF 8 · NAME THE INK</span><div class="word-stimulus" style="color:${colors[ink]}">${colorNames[word]}</div>`;options.innerHTML=colorNames.map((name,i)=>button(name,`lab-stroop:${i}`,'secondary')).join('');}
  async function handle(e){const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;
    if(action==='lab-stroop-start'){trial=0;correct=0;showTrial();}
    if(action.startsWith('lab-stroop:')&&trial<trials.length){if(+action.split(':')[1]===trials[trial][1])correct++;trial++;showTrial();}
    if(action==='lab-sound'){try{if(on){gain.gain.setTargetAtTime(0,audio.currentTime,.03);on=false;}else{if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(!A)throw new Error('Audio unavailable');audio=new A();osc=audio.createOscillator();gain=audio.createGain();gain.gain.value=0;osc.connect(gain);gain.connect(audio.destination);osc.start();}await audio.resume();gain.gain.setTargetAtTime(.025,audio.currentTime,.03);on=true;update();}root.querySelector('#sound-status').textContent=on?'Playing quietly':'Sound is off';e.target.closest('button').innerHTML=icon('sound')+(on?' Stop sound':' Play quietly');}catch{root.querySelector('#sound-status').textContent='Audio is unavailable here. You can still explore the waveform.';}}
  }
  root.addEventListener('input',update);root.addEventListener('change',update);root.addEventListener('click',handle);update();
  return ()=>{root.removeEventListener('input',update);root.removeEventListener('change',update);root.removeEventListener('click',handle);if(audio)audio.close().catch(()=>{});};
}
