import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const args=process.argv.slice(2),pi=args.indexOf('--port'),port=Number(pi>=0?args[pi+1]:process.env.PORT||4173);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.json':'application/json','.webmanifest':'application/manifest+json','.md':'text/plain; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p==='/__mobile-qa'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Elsewhere · mobile QA</title><style>body{background:#222;margin:20px;font:14px system-ui;color:white}iframe{border:1px solid #555;border-radius:22px;background:#0d1515;display:block}select{margin:0 0 15px;padding:10px;font:inherit}label{display:block;margin-bottom:8px}</style><label for="size">Test viewport width</label><select id="size"><option value="390">390 px · phone</option><option value="320">320 px · small phone</option><option value="768">768 px · tablet</option><option value="1024">1024 px · desktop</option></select><iframe title="Elsewhere mobile" id="mobile" src="/repo-test/" width="390" height="844"></iframe><script>document.getElementById('size').onchange=e=>document.getElementById('mobile').width=e.target.value;</script>`);return;}
  if(p.startsWith('/repo-test/'))p=p.slice('/repo-test'.length);if(p.endsWith('/'))p+='index.html';const target=path.resolve(root,'.'+p);if(target!==root&&!target.startsWith(root+path.sep)){res.writeHead(403);res.end('Forbidden');return;}if(!(await stat(target)).isFile())throw new Error('Not found');const data=await readFile(target);res.writeHead(200,{'Content-Type':types[path.extname(target)]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});res.end(data);}catch{res.writeHead(404,{'Content-Type':'text/plain'});res.end('Not found');}});
server.listen(port,'0.0.0.0',()=>console.log(`Elsewhere preview ready on port ${port}`));
process.on('SIGTERM',()=>server.close());
